### ISSUE TITLE
Unable to submit normal captcha using base64

### ISSUE THREAD

**Issue by bylee-123** [2captcha/2captcha-php#1]
Referencing the code from examples/normal_base64.php yields an error `Undefined index: method`

Traced the error back to here where `$files` returns `null`:
https://github.com/2captcha/2captcha-php/blob/f854b26a67b6d42a1ebc99c7c9d9bd4e714745e1/src/TwoCaptcha.php#L444

Causing this line to throw an error:
https://github.com/2captcha/2captcha-php/blob/f854b26a67b6d42a1ebc99c7c9d9bd4e714745e1/src/TwoCaptcha.php#L447

**Comment by anurak-kg** [comment]
+1 I have the same problem.

**Comment by 2captcha** [comment]
fixed in the latest commit
