### ISSUE TITLE
Every time geting error ERROR_KEY_DOES_NOT_EXIST

### ISSUE THREAD

**Issue by SargisBeglaryan** [2captcha/2captcha-php#14]
Code example
```python
$solver = new \TwoCaptcha\TwoCaptcha('key_value');

try {
    $result = $solver->recaptcha([
        'sitekey' => '6LfD3PIbAAAAAJs_eEHvoOl75_83eXSqpPSRFJ_u',
        'url'     => 'https://2captcha.com/demo/recaptcha-v2',
    ]);
} catch (\Exception $e) {
    die($e->getMessage());
}
```

```python
$solver = new \TwoCaptcha\TwoCaptcha('key_value');

try {
    $result = $solver->turnstile([
        'sitekey' => '0x4AAAAAAAVrOwQWPlm3Bnr5',
        'url'     => 'https://2captcha.com/demo/cloudflare-turnstile',
    ]);
} catch (\Exception $e) {
    die($e->getMessage());
}
```

![uMlesOP8T1Wr3g90HFa4pg](https://github.com/2captcha/2captcha-php/assets/14293395/5be4ae55-d28e-46f1-ba1b-ecaec721a1df)
![5tdsKkXrRKCxljXHBYS1gw](https://github.com/2captcha/2captcha-php/assets/14293395/749025ae-4bab-410d-95b9-a39662148404)

**Comment by kratzky** [comment]
It's not a good idea to publish your API key, but I can't find a user with this API key in our database and it may be the reason why you receive the error. 
Follow the recommendations from the API docs:
https://2captcha.com/api-docs/error-codes
https://2captcha.com/2captcha-api#error_handling

If you are 100% sure you use the proper API key value, check your hosts file for any entries with 2captcha.com or rucaptcha.com domains and remove them.
